import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const styles = readFileSync(join(process.cwd(), 'src', 'styles.css'), 'utf8').replaceAll('\r\n', '\n')

describe('responsive layout CSS', () => {
  it('defines a focused Go studio design system', () => {
    expect(styles).toContain('--ink: #1a1a2e;')
    expect(styles).toContain('--paper: #f8f5ec;')
    expect(styles).toContain('--surface: #faf8f4;')
    expect(styles).toContain('--table: #1a472a;')
    expect(styles).toContain('--board-wood: #d4a45e;')
    expect(styles).toContain('--signal: #c2410c;')
    expect(styles).toContain('--frame: #1e293b;')
    expect(styles).toContain('--app-width: 100dvw;')
    expect(styles).toContain('font-family: "Inter", "Segoe UI", ui-sans-serif')
    expect(styles).toContain('background:\n    radial-gradient(circle at 20% 50%')
  })

  it('prevents accidental mobile long-press selection from the root while keeping form text selectable', () => {
    expect(styles).toContain('html,\nbody,\n#root {\n  height: 100%;\n  overflow: hidden;\n  background: var(--paper);\n  overscroll-behavior: none;\n  touch-action: manipulation;\n  -webkit-touch-callout: none;\n  -webkit-tap-highlight-color: transparent;\n  -webkit-user-select: none;\n  user-select: none;')
    expect(styles).toContain('touch-action: manipulation;')
    expect(styles).toContain('-webkit-tap-highlight-color: transparent;')
    expect(styles).toContain('-webkit-touch-callout: none;')
    expect(styles).toContain('-webkit-user-select: none;')
    expect(styles).toContain('user-select: none;')
    expect(styles).toContain('input,\ntextarea {\n  font: inherit;\n  -webkit-touch-callout: default;\n  -webkit-user-select: text;\n  user-select: text;')
  })

  it('fixes the cockpit to the viewport with the board as the dominant work surface', () => {
    expect(styles).toContain('body {\n  margin: 0;')
    expect(styles).toContain('--app-height: 100dvh;')
    expect(styles).toContain('--app-content-height: calc(var(--app-height) - var(--app-safe-top) - var(--app-safe-bottom));')
    expect(styles).toContain('--app-safe-bottom: env(safe-area-inset-bottom, 0px);')
    expect(styles).toContain('html,\nbody,\n#root {\n  height: 100%;\n  overflow: hidden;\n  background: var(--paper);')
    expect(styles).toContain('.app-layout {\n  height: var(--app-height);')
    expect(styles).toContain('width: var(--app-width);')
    expect(styles).toContain('container-type: size;\n  container-name: app-layout;')
    expect(styles).toContain('padding: var(--app-safe-top) var(--app-safe-right) var(--app-safe-bottom) var(--app-safe-left);')
    expect(styles).toContain('grid-template-columns: 48px 1fr 48px minmax(340px, 420px);')
    expect(styles).toContain('.game-sidebar,\n.board-stage,\n.action-rail,\n.analysis-rail {\n  min-width: 0;\n  min-height: 0;\n  box-sizing: border-box;')
    expect(styles).toContain('.game-sidebar {\n  position: relative;\n  z-index: 4;\n  display: grid;\n  grid-template-rows: auto minmax(0, 1fr) auto;')
    expect(styles).toContain('height: 100%;\n  box-sizing: border-box;')
    expect(styles).toContain('.game-sidebar h1 {\n  display: none;')
    expect(styles).toContain('.sidebar-actions {\n  display: flex;\n  flex-direction: column;')
    expect(styles).toContain('.sidebar-analysis {\n  grid-row: 3;\n  align-self: end;')
    expect(styles).toContain('.analysis-action-button {\n  width: 100%;\n  max-width: 36px;\n  height: 36px;')
    expect(styles).toContain('display: grid;\n  place-items: center;')
    expect(styles).toContain('.game-list {\n  display: none;')
    expect(styles).toContain('.game-sidebar.expanded .game-list {\n  position: fixed;')
    expect(styles).toContain('.board-stage {\n  position: relative;')
    expect(styles).toContain('justify-items: center;')
    expect(styles).toContain('--board-zone: var(--paper);')
    expect(styles).toContain('background: var(--board-zone);')
    expect(styles).toContain('.board-layout {\n  display: grid;\n  width: 100%;\n  height: 100%;')
    expect(styles).toContain('.board-matchup {\n  display: flex;\n  align-items: center;')
    expect(styles).toContain('.board-player-stone-black {\n  border-color: #050505;')
    expect(styles).toContain('.board-player-stone-white {\n  border-color: #9ca3af;')
    expect(styles).toContain('.board-result {\n  color: var(--table);')
    expect(styles).toContain('.board-frame {')
    expect(styles).toContain('--board-frame-clearance: 16px;')
    expect(styles).toContain('container-type: size;\n  container-name: board-frame;')
    expect(styles).toContain('.go-board {\n  position: relative;')
    expect(styles).toContain('width: min(calc(100cqw - var(--board-frame-clearance)), calc(100cqh - var(--board-frame-clearance)));')
    expect(styles).toContain('height: min(calc(100cqw - var(--board-frame-clearance)), calc(100cqh - var(--board-frame-clearance)));')
    expect(styles).toContain('max-width: 100%;')
    expect(styles).toContain('filter: drop-shadow(0 20px 40px rgb(42 30 14 / 0.25));')
    expect(styles).toContain('.action-rail {')
    expect(styles).toContain('.navigation-controls {')
    expect(styles).toContain('.navigation-controls button:active {\n  transform: translateY(1px) scale(0.98);')
    expect(styles).toContain('@media (hover: hover) and (pointer: fine) {\n  .navigation-controls button:hover {\n    background: var(--surface-raised);\n    border-color: var(--line-strong);')
    expect(styles).toContain('@media (hover: none), (pointer: coarse) {\n  button:not(:disabled):hover {\n    transform: none;')
    expect(styles).toContain('.navigation-controls button:hover {\n    border-color: var(--line);\n    background: var(--surface);')
    expect(styles).not.toContain('.navigation-controls button:hover,\n.analysis-tab:hover')
    expect(styles).toContain('.move-number-stone {')
    expect(styles).toContain('.try-action-button {\n  border-radius: 50%;')
    expect(styles).toContain('.navigation-controls .try-action-enter {\n  border-color: #047857;\n  background: #059669;')
    expect(styles).toContain('.navigation-controls .try-action-exit {\n  border-color: #b91c1c;\n  background: #dc2626;')
  })

  it('keeps analysis information dense, scannable, and scroll-contained', () => {
    expect(styles).toContain('.analysis-rail {\n  display: grid;\n  grid-template-rows: minmax(188px, 264px) minmax(0, 1fr);')
    expect(styles).toContain('.analysis-overview {\n  grid-template-rows: 22px minmax(0, 1fr);')
    expect(styles).toContain('.analysis-summary {\n  display: grid;')
    expect(styles).toContain('grid-template-columns: repeat(3, minmax(0, 1fr));')
    expect(styles).toContain('.summary-metric {')
    expect(styles).toContain('height: 22px;\n  display: flex;\n  align-items: center;\n  justify-content: center;')
    expect(styles).toContain('border: 1px solid rgb(212 201 184 / 0.54);\n  border-radius: 999px;\n  background: rgb(250 248 244 / 0.72);')
    expect(styles).toContain('.rail-section-body {\n  min-height: 0;\n  overflow: auto;')
    expect(styles).toContain('.winrate-chart {\n  width: 100%;\n  height: 100%;\n  min-height: 88px;')
    expect(styles).toContain('.chart-label-layer {\n  position: absolute;\n  inset: 0;')
    expect(styles).toContain('.chart-axis-label,\n.chart-tick-label {\n  position: absolute;\n  color: var(--muted);\n  font-family: "Inter", "Segoe UI", ui-sans-serif, system-ui, sans-serif;')
    expect(styles).toContain('font-stretch: normal;\n  font-size: 9px;\n  font-weight: 600;\n  line-height: 1;\n  letter-spacing: 0;')
    expect(styles).toContain('.analysis-detail-tabs {\n  grid-template-rows: 24px minmax(0, 1fr);')
    expect(styles).toContain('height: 100%;\n  box-sizing: border-box;')
    expect(styles).toContain('.analysis-tab-list {\n  width: max-content;\n  max-width: 100%;\n  height: 100%;\n  box-sizing: border-box;\n  display: grid;\n  grid-auto-flow: column;')
    expect(styles).toContain('.analysis-tab {\n  min-width: 42px;\n  height: 100%;')
    expect(styles).toContain('.analysis-tab[aria-selected=\'true\'] {\n  background: var(--surface);\n  color: var(--ink);')
  })

  it('keeps imported game rows aligned with compact icon actions', () => {
    expect(styles).toContain('width: min(520px, calc(100vw - 72px));')
    expect(styles).toContain('.game-row {\n  display: grid;\n  grid-template-columns: minmax(0, 1fr) 34px 34px;')
    expect(styles).toContain('.game-title span,\n.game-title small {\n  overflow: hidden;\n  text-overflow: ellipsis;\n  white-space: nowrap;')
    expect(styles).toContain('.game-title-meta {\n  display: flex;\n  flex-wrap: wrap;')
    expect(styles).toContain('.game-analysis-badge {\n  min-width: max-content;')
    expect(styles).toContain('.game-row-action {\n  width: 34px;\n  height: 34px;')
    expect(styles).toContain('.game-row-action.danger')
  })

  it('keeps portrait import controls styled for compact dialogs', () => {
    expect(styles).toContain('.portrait-import-button {\n  min-height: 42px;')
    expect(styles).toContain('.import-dialog {\n  position: fixed;\n  inset: 0;\n  z-index: 40;')
    expect(styles).toContain('.import-dialog-body {\n  width: min(320px, 100%);')
  })

  it('keeps mobile landscape navigation beside the board and import visible', () => {
    expect(styles).toContain('@media (orientation: landscape) and (max-height: 520px),\n  (orientation: landscape) and (max-width: 1220px) and (pointer: coarse)')
    expect(styles).not.toContain('--app-height: 100svh;')
    expect(styles).toContain('grid-template-columns: 44px 1fr 44px minmax(240px, 320px);')
    expect(styles).toContain('height: var(--app-height);')
    expect(styles).toContain('.board-stage {\n    padding: 2px 4px;\n    height: 100%;\n    max-height: var(--app-content-height);')
    expect(styles).toContain('.board-frame {\n    --board-frame-clearance: 4px;')
    expect(styles).toContain('.game-sidebar.expanded .game-list')
    expect(styles).toContain('.action-rail {')
    expect(styles).toContain('.analysis-rail {\n    grid-template-rows: minmax(150px, 170px) minmax(0, 1fr);\n    gap: 6px;')
    expect(styles).toContain('.analysis-overview {\n    grid-template-rows: 24px minmax(0, 1fr);')
    expect(styles).toContain('.winrate-chart {\n    height: clamp(126px, calc(var(--app-content-height) * 0.32), 144px);\n    min-height: 0;')
    expect(styles).toContain('.analysis-detail-tabs {\n    grid-template-rows: 22px minmax(0, 1fr);\n    gap: 3px;')
    expect(styles).toContain('.analysis-tab {\n    min-width: 34px;\n    height: 100%;')
    expect(styles).toContain('.candidate-row,\n  .bad-move {\n    min-height: 28px;')
  })

  it('treats 11 inch iPad landscape as a tablet workspace with a square board box', () => {
    expect(styles).toContain('@media (orientation: landscape) and (max-height: 520px),\n  (orientation: landscape) and (max-width: 1220px) and (pointer: coarse)')
    expect(styles).toContain('@media (min-width: 1101px) and (max-width: 1220px) and (orientation: landscape)')
    expect(styles).toContain('.board-stage {\n    max-height: var(--app-content-height);')
    expect(styles).toContain('.go-board {\n  position: relative;\n  z-index: 1;\n  width: min(calc(100cqw - var(--board-frame-clearance)), calc(100cqh - var(--board-frame-clearance)));')
  })

  it('keeps narrow phone landscape focused on the board instead of squeezing three rails', () => {
    expect(styles).toContain('@media (orientation: landscape) and (max-width: 820px) {')
    expect(styles).toContain('grid-template-columns: 44px 1fr 44px;')
    expect(styles).toContain('.analysis-rail {\n    display: none;')
    expect(styles).toContain('.game-sidebar {\n    grid-template-rows: 40px minmax(0, 1fr) 40px;')
    expect(styles).toContain('.analysis-action-button {\n    width: 36px;\n    height: 32px;')
    expect(styles).toContain('.board-frame {\n    --board-frame-clearance: 4px;')
  })

  it('keeps the portrait workspace ordered as toolbar, game info, board, controls, then analysis', () => {
    expect(styles).toContain('@media (orientation: portrait) and (max-width: 820px) {')
    expect(styles).toContain('@container app-layout (max-aspect-ratio: 1 / 1) and (max-width: 820px) {')
    expect(styles).toContain('grid-template-columns: 1fr;')
    expect(styles).toContain('grid-template-rows: auto minmax(0, 46vh) auto minmax(150px, 1fr);')
    expect(styles).toContain('.rotate-prompt {\n    display: none;')
    expect(styles).not.toContain('@media (orientation: portrait) and (max-width: 820px) {\n  .app-layout {\n    display: none;')
    expect(styles).toContain('.game-sidebar {\n    grid-row: 1;\n    height: auto;\n    min-height: 40px;\n    grid-template-columns: minmax(0, 1fr) auto;')
    expect(styles).toContain('.board-stage {\n    grid-row: 2;\n    padding: 2px 6px 0;\n    max-height: none;\n    overflow: visible;\n    z-index: 1;')
    expect(styles).toContain('.board-layout {\n    grid-template-columns: 1fr;\n    grid-template-rows: min-content minmax(0, 1fr);\n    gap: 2px;')
    expect(styles).toContain('.board-info {\n    order: 1;\n    gap: 4px;')
    expect(styles).toContain('.board-frame {\n    --board-frame-clearance: 4px;\n    order: 2;')
    expect(styles).toContain('--portrait-chart-height: 88px;')
    expect(styles).toContain('--portrait-overview-padding-top: 2px;')
    expect(styles).toContain('--portrait-overview-height: calc(var(--portrait-summary-height) + var(--portrait-overview-gap) + var(--portrait-chart-height) + var(--portrait-overview-padding-top) + var(--portrait-overview-padding-bottom));')
    expect(styles).toContain('.action-rail {\n    grid-row: 3;\n    position: relative;\n    z-index: 3;\n    padding: 0 8px 8px;\n    background: transparent;\n    border: 0;')
    expect(styles).toContain('.navigation-controls {\n    width: max-content;\n    max-width: calc(100% - 16px);')
    expect(styles).toContain('border-radius: 999px;\n    background: transparent;\n    box-shadow: none;')
    expect(styles).toContain('overflow: visible;')
    expect(styles).not.toContain('overflow-x: auto;\n    overflow-y: hidden;')
    expect(styles).toContain('.navigation-controls button {\n    width: 32px;\n    min-width: 32px;\n    max-width: 32px;\n    height: 30px;')
    expect(styles).toContain('text-overflow: clip;')
    expect(styles).toContain('.navigation-controls .try-action-button {\n    width: 30px;\n    min-width: 30px;\n    max-width: 30px;\n    height: 30px;\n    padding: 0;')
    expect(styles).toContain('.move-number-stone {\n    width: 30px;\n    height: 30px;')
    expect(styles).toContain('.analysis-rail {\n    grid-row: 4;\n    min-height: 0;\n    max-height: none;\n    grid-template-rows: var(--portrait-overview-height) minmax(0, 1fr);')
    expect(styles).toContain('padding: 4px 6px 6px;\n    background: var(--board-zone);\n    overflow: hidden;')
    expect(styles).toContain('.analysis-overview,\n  .analysis-detail-tabs {\n    border-color: transparent;\n    background: transparent;\n    box-shadow: none;')
    expect(styles).toContain('.analysis-overview {\n    grid-template-rows: var(--portrait-summary-height) var(--portrait-chart-height);\n    gap: var(--portrait-overview-gap);\n    padding: var(--portrait-overview-padding-top) 6px var(--portrait-overview-padding-bottom);')
    expect(styles).toContain('.chart-body {\n    height: var(--portrait-chart-height);\n    overflow: visible;')
    expect(styles).toContain('.winrate-chart {\n    height: var(--portrait-chart-height);\n    min-height: 0;')
    expect(styles).toContain('.sidebar-analysis {\n    grid-column: 2;')
  })

  it('keeps app layout responsive when mobile rotation leaves viewport media queries stale', () => {
    expect(styles).toContain('@container app-layout (min-aspect-ratio: 1 / 1) and (max-width: 1220px) {')
    expect(styles).toContain('@container app-layout (min-aspect-ratio: 1 / 1) and (max-height: 520px) {')
    expect(styles).toContain('@container app-layout (min-aspect-ratio: 1 / 1) and (max-width: 820px) {')
    expect(styles).toContain('@container app-layout (min-aspect-ratio: 1 / 1) and (min-width: 1101px) and (max-width: 1220px) {')
    expect(styles).toContain('.board-stage {\n    grid-row: auto;\n    padding: 2px 4px;')
    expect(styles).toContain('.board-layout {\n    grid-template-columns: auto minmax(0, 1fr);\n    grid-template-rows: none;')
    expect(styles).toContain('.board-frame {\n    --board-frame-clearance: 4px;\n    order: initial;')
    expect(styles).toContain('.board-info {\n    order: initial;')
  })
})
