import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const styles = readFileSync(join(process.cwd(), 'src', 'styles.css'), 'utf8').replaceAll('\r\n', '\n')

describe('responsive layout CSS', () => {
  it('defines a contextual titlebar for app pages', () => {
    expect(styles).toContain('.contextual-titlebar {\n  min-width: 0;\n  min-height: var(--topbar-height);\n  display: grid;')
    expect(styles).toContain('grid-template-columns: var(--ui-btn-size) minmax(0, 1fr) var(--ui-btn-size);')
  })

  it('defines a focused Go studio design system', () => {
    expect(styles).toContain('--ink: #1a1a2e;')
    expect(styles).toContain('--paper: #f8f5ec;')
    expect(styles).toContain('--surface: #faf8f4;')
    expect(styles).toContain('--table: #1a472a;')
    expect(styles).toContain('--board-wood: #d4a45e;')
    expect(styles).toContain('--signal: #c2410c;')
    expect(styles).toContain('--frame: #1e293b;')
    expect(styles).toContain('--analysis-pill-shell: rgb(212 201 184 / 0.28);')
    expect(styles).toContain('--analysis-pill-border: rgb(212 201 184 / 0.72);')
    expect(styles).toContain('--analysis-pill-surface: rgb(250 248 244 / 0.84);')
    expect(styles).toContain('--analysis-pill-group-width: min(100%, 252px);')
    expect(styles).toContain('--analysis-pill-height: 22px;')
    expect(styles).toContain('--app-width: 100dvw;')
    expect(styles).toContain('font-family: "Inter", "Segoe UI", ui-sans-serif')
    expect(styles).toContain('background:\n    radial-gradient(circle at 20% 50%')
  })

  it('prevents accidental mobile long-press selection from the root while keeping form text selectable', () => {
    expect(styles).toContain('html,\nbody,\n#root {\n  height: 100%;\n  overflow: hidden;\n  background: var(--paper);\n  overscroll-behavior: none;\n  touch-action: manipulation;\n  -webkit-touch-callout: none;\n  -webkit-tap-highlight-color: transparent;\n  -webkit-user-select: none;\n  user-select: none;')
    expect(styles).toContain('touch-action: manipulation;')
    expect(styles).toContain('-webkit-tap-highlight-color: transparent;')
    expect(styles).toContain('-webkit-touch-callout: none;')
    expect(styles).toContain('-webkit-user-select: none;')
    expect(styles).toContain('user-select: none;')
    expect(styles).toContain('input,\ntextarea {\n  font: inherit;\n  -webkit-touch-callout: default;\n  -webkit-user-select: text;\n  user-select: text;')
  })

  it('fixes the cockpit to the viewport with the board as the dominant work surface', () => {
    expect(styles).toContain('body {\n  margin: 0;')
    expect(styles).toContain('--app-height: 100dvh;')
    expect(styles).toContain('--analysis-detail-preview-height: 64px;')
    expect(styles).toContain('--analysis-bottom-height: calc(var(--analysis-overview-height) + var(--analysis-detail-preview-height));')
    expect(styles).toContain('--wide-analysis-bottom-height: var(--analysis-overview-height);')
    expect(styles).toContain('--side-analysis-height: max(var(--analysis-bottom-height), min(22dvh, 280px));')
    expect(styles).toContain('--app-content-height: calc(var(--app-height) - var(--app-safe-top) - var(--app-safe-bottom));')
    expect(styles).toContain('--app-safe-bottom: env(safe-area-inset-bottom, 0px);')
    expect(styles).toContain('html,\nbody,\n#root {\n  height: 100%;\n  overflow: hidden;\n  background: var(--paper);')
    expect(styles).toContain('.app-layout {\n  position: relative;\n  height: var(--app-height);')
    expect(styles).toContain('width: var(--app-width);')
    expect(styles).toContain('container-type: size;\n  container-name: app-layout;')
    expect(styles).toContain('padding: var(--app-safe-top) var(--app-safe-right) var(--app-safe-bottom) var(--app-safe-left);')
    expect(styles).toContain('grid-template-columns: 1fr;')
    expect(styles).toContain('grid-template-rows: auto auto auto minmax(var(--analysis-bottom-height), 1fr);')
    expect(styles).toContain('.app-layout.side-action-layout {\n  grid-template-columns: 1fr;\n  grid-template-rows: auto minmax(0, 1fr) var(--side-analysis-height);')
    expect(styles).toContain('.game-sidebar,\n.board-stage,\n.action-rail,\n.analysis-rail {\n  min-width: 0;\n  min-height: 0;\n  box-sizing: border-box;')
    expect(styles).toContain('.game-sidebar {\n  position: relative;\n  z-index: 4;\n  display: grid;\n  grid-template-rows: auto minmax(0, 1fr) auto;')
    expect(styles).toContain('height: 100%;\n  box-sizing: border-box;')
    expect(styles).toContain('.game-sidebar h1 {\n  display: none;')
    expect(styles).toContain('.sidebar-actions {\n  display: flex;\n  flex-direction: column;')
    expect(styles).toContain('.sidebar-toggle-actions {\n  display: grid;\n  place-items: center;')
    expect(styles).toContain('.sidebar-analysis {\n  grid-row: 3;\n  align-self: end;')
    expect(styles).toContain('.analysis-action-button {\n  width: var(--ui-btn-size);\n  min-width: var(--ui-btn-size);\n  max-width: none;\n  height: var(--ui-btn-size);')
    expect(styles).toContain('display: grid;\n  place-items: center;')
    expect(styles).toContain('.app-page-workspace {\n  position: fixed;\n  inset: calc(var(--app-safe-top) + var(--topbar-height))')
    expect(styles).toContain('.app-layout.page-open .board-stage,\n.app-layout.page-open .action-rail,\n.app-layout.page-open .analysis-rail {\n  pointer-events: none;')
    expect(styles).toContain('.board-stage {\n  position: relative;')
    expect(styles).toContain('justify-items: center;')
    expect(styles).toContain('.app-layout:not(.side-action-layout) .board-stage {\n  container-type: inline-size;\n  grid-template-rows: auto;\n  align-content: start;\n  align-items: start;')
    expect(styles).toContain('--board-zone: var(--paper);')
    expect(styles).toContain('background: var(--board-zone);')
    expect(styles).toContain('.board-layout {\n  display: grid;\n  width: 100%;\n  height: 100%;')
    expect(styles).toContain('.app-layout:not(.side-action-layout) .board-layout {\n  height: auto;\n  align-content: start;\n  grid-template-rows: min-content auto;')
    expect(styles).toContain('.board-matchup {\n  display: flex;\n  flex-direction: column;\n  align-items: flex-start;')
    expect(styles).toContain('.board-player-stone-black {\n  border-color: #050505;')
    expect(styles).toContain('.board-player-stone-white {\n  border-color: #9ca3af;')
    expect(styles).toContain('.board-result {\n  color: var(--table);')
    expect(styles).toContain('.board-frame {')
    expect(styles).toContain('--board-frame-inline-clearance: 16px;')
    expect(styles).toContain('--board-frame-block-clearance: 16px;')
    expect(styles).toContain('.app-layout:not(.side-action-layout) .board-frame {\n  height: 100cqw;\n  aspect-ratio: 1;\n  align-self: start;')
    expect(styles).toContain('container-type: size;\n  container-name: board-frame;')
    expect(styles).toContain('.go-board {\n  position: relative;')
    expect(styles).toContain('width: min(calc(100cqw - var(--board-frame-inline-clearance)), calc(100cqh - var(--board-frame-block-clearance)));')
    expect(styles).toContain('height: min(calc(100cqw - var(--board-frame-inline-clearance)), calc(100cqh - var(--board-frame-block-clearance)));')
    expect(styles).toContain('max-width: 100%;')
    expect(styles).toContain('filter: drop-shadow(0 20px 40px rgb(42 30 14 / 0.25));')
    expect(styles).toContain('.action-rail {')
    expect(styles).toContain('.side-action-layout .board-frame {\n  --board-frame-inline-clearance: calc((var(--side-action-width, 42px) + var(--side-action-gap, 18px) + var(--side-action-edge-gap, 12px)) * 2);\n  --board-frame-block-clearance: 16px;')
    expect(styles).toContain('.side-action-layout .action-rail {\n  grid-row: 1 / -1;\n  grid-column: 1 / -1;\n  position: absolute;\n  left: var(--side-action-left, 0px);\n  top: var(--side-action-top, 0px);\n  width: var(--side-action-width, 36px);')
    expect(styles).toContain('.side-action-layout .navigation-controls {\n  width: var(--side-action-width, 36px);\n  max-width: var(--side-action-width, 36px);\n  box-sizing: border-box;\n  grid-auto-flow: row;\n  grid-auto-rows: var(--side-action-row-height, 36px);')
    expect(styles).toContain('.side-action-layout .navigation-controls button,\n.side-action-layout .navigation-controls .try-action-button,\n.side-action-layout .move-number-stone {\n  width: var(--side-action-row-height, 36px);\n  min-width: var(--side-action-row-height, 36px);\n  max-width: var(--side-action-row-height, 36px);\n  height: var(--side-action-row-height, 36px);\n  box-sizing: border-box;\n  justify-self: center;')
    expect(styles).toContain('.navigation-controls {')
    expect(styles).toContain('.navigation-controls button:active {\n  transform: translateY(1px) scale(0.98);')
    expect(styles).toContain('@media (hover: hover) and (pointer: fine) {\n  .navigation-controls button:hover {\n    background: var(--surface-raised);\n    border-color: var(--line-strong);')
    expect(styles).toContain('@media (hover: none), (pointer: coarse) {\n  button:not(:disabled):hover {\n    transform: none;')
    expect(styles).toContain('.navigation-controls button:hover {\n    border-color: var(--line);\n    background: var(--surface);')
    expect(styles).not.toContain('.navigation-controls button:hover,\n.analysis-tab:hover')
    expect(styles).toContain('.move-number-stone {')
    expect(styles).toContain('.try-action-button {\n  border-radius: 50%;')
    expect(styles).toContain('.navigation-controls .try-action-ready {\n  border-color: #047857;\n  background: #059669;')
    expect(styles).toContain('.navigation-controls .try-action-preview {\n  border-color: #9ca3af;\n  background: #d1d5db;\n  color: #4b5563;')
    expect(styles).toContain('.navigation-controls .try-action-exit {\n  border-color: #b91c1c;\n  background: #dc2626;')
  })

  it('keeps analysis information dense, scannable, and scroll-contained', () => {
    expect(styles).toContain('.analysis-rail {\n  display: grid;\n  grid-template-rows: var(--analysis-overview-height) minmax(0, 1fr);')
    expect(styles).toContain('.analysis-overview {\n  grid-template-rows: 22px minmax(0, 1fr);')
    expect(styles).toContain('.analysis-summary,\n.analysis-tab-list {\n  width: var(--analysis-pill-group-width);\n  max-width: 100%;\n  height: var(--analysis-pill-height);')
    expect(styles).toContain('grid-template-columns: repeat(3, minmax(0, 1fr));')
    expect(styles).toContain('border: 1px solid var(--analysis-pill-border);\n  border-radius: 999px;\n  background: var(--analysis-pill-shell);')
    expect(styles).toContain('.summary-metric {')
    expect(styles).toContain('height: 100%;\n  min-height: 0;\n  display: flex;\n  align-items: center;\n  justify-content: center;')
    expect(styles).toContain('border: 0;\n  border-radius: 999px;\n  background: transparent;')
    expect(styles).toContain('box-shadow: none;')
    expect(styles).toContain('.rail-section-body {\n  min-height: 0;\n  overflow: auto;')
    expect(styles).toContain('overscroll-behavior: contain;\n  -webkit-overflow-scrolling: touch;\n  touch-action: pan-y;')
    expect(styles).toContain('.echarts-chart {\n  width: 100%;\n  height: 100%;\n  min-height: 88px;')
    expect(styles).toContain('.chart-click-layer {\n  position: absolute;\n  left: 8.75%;')
    expect(styles).toContain('.chart-hit-target {\n  position: absolute;\n  top: 0;\n  bottom: 0;')
    expect(styles).toContain('.analysis-detail-tabs {\n  grid-template-rows: 24px minmax(0, 1fr);')
    expect(styles).toContain('height: 100%;\n  box-sizing: border-box;')
    expect(styles).toContain('.analysis-tab {\n  min-width: 0;\n  height: 100%;')
    expect(styles).toContain('.analysis-tab[aria-selected=\'true\'] {\n  background: var(--analysis-pill-surface);\n  color: var(--ink);')
  })

  it('opens the local game library in the shared page workspace', () => {
    expect(styles).toContain('--topbar-height: 42px;')
    expect(styles).toContain('.app-page-body {\n  min-width: 0;\n  min-height: 0;\n  width: min(1040px, 100%);')
    expect(styles).toContain('.game-library-page {\n  padding: 12px;')
    expect(styles).toContain('.game-list-shell {\n  width: min(1040px, 100%);')
    expect(styles).toContain('.game-list-body.yuanluobo-record-list {')
    expect(styles).toContain('.game-library-page .game-row.yuanluobo-record-row {\n  grid-template-columns: minmax(0, 1fr) auto;')
    expect(styles).toContain('.game-row-actions {\n  display: flex;')
    expect(styles).toContain('.game-row-open {\n  grid-column: 1;')
    expect(styles).toContain('.game-row.yuanluobo-record-row::before {')
    expect(styles).not.toContain('.game-row .yuanluobo-result-watermark {')
    expect(styles).toContain('.game-analysis-badge {\n  min-width: max-content;')
    expect(styles).toContain('.game-row-action {\n  width: 34px;\n  height: 34px;')
    expect(styles).toContain('.game-row-action.danger')
  })

  it('aligns worker settings with the compact local game library layout', () => {
    expect(styles).toContain('.settings-page .settings-section {\n  min-height: 0;\n  height: 100%;')
    expect(styles).toContain('.worker-status-summary {\n  min-height: 58px;\n  display: grid;\n  grid-template-columns: minmax(0, 1fr) auto;')
    expect(styles).toContain('.worker-summary-metrics {\n  display: grid;\n  grid-template-columns: repeat(3, minmax(72px, auto));')
    expect(styles).toContain('.worker-row {\n  position: relative;\n  min-height: 72px;\n  display: grid;\n  grid-template-columns: minmax(220px, 0.9fr) minmax(360px, 1.4fr) auto;')
    expect(styles).toContain('.worker-controls {\n  display: grid;\n  grid-template-columns: minmax(180px, 1fr) 88px auto;')
    expect(styles).toContain('.worker-row::before {\n  content: "";')
  })

  it('keeps import controls styled as page content', () => {
    expect(styles).toContain('.portrait-import-button {\n  min-height: 42px;')
    expect(styles).toContain('.import-page {\n  align-content: start;\n  gap: 18px;')
    expect(styles).toContain('.import-page-description {\n  max-width: 560px;')
    expect(styles).toContain('.import-source-grid {\n  display: grid;')
    expect(styles).toContain('.yuanluobo-login-layout {\n  grid-template-columns: 1fr;')
    expect(styles).toContain('.yuanluobo-browser {\n  grid-template-rows: auto auto minmax(0, 1fr) auto;')
    expect(styles).toContain('.yuanluobo-browser-body {\n  width: min(1040px, 100%);')
    expect(styles).toContain('.yuanluobo-panel .yuanluobo-record-row {\n  position: relative;')
    expect(styles).toContain('.yuanluobo-result-watermark.win')
    expect(styles).toContain('.yuanluobo-result-watermark.loss')
    expect(styles).toContain('.yuanluobo-result-watermark.draw')
  })

  it('gives the yuanluobo browser a polished compact library treatment', () => {
    expect(styles).toContain('.yuanluobo-browser::before {')
    expect(styles).toContain('background-size: 28px 28px;')
    expect(styles).toContain('.yuanluobo-filter-bar,\n.yuanluobo-record-list,\n.yuanluobo-pager {\n  width: min(1040px, 100%);')
    expect(styles).toContain('.yuanluobo-filter-bar {\n  display: grid;\n  grid-template-columns: repeat(2, minmax(0, 320px));')
    expect(styles).toContain('.yuanluobo-panel .yuanluobo-filter-trigger {\n  min-height: 76px;')
    expect(styles).toContain('.yuanluobo-filter-icon {\n  width: 42px;\n  height: 42px;\n  display: grid;\n  place-items: center;\n  color: #9a6a2e;')
    expect(styles).not.toContain('background: rgb(194 141 64 / 0.12);')
    expect(styles).toContain('.yuanluobo-record-toolbar {\n  width: min(1040px, 100%);')
    expect(styles).not.toContain('.yuanluobo-record-toolbar button')
    expect(styles).toContain('.yuanluobo-record-list {\n  min-height: 0;\n  flex: 1 1 auto;\n  display: grid;\n  align-content: start;\n  gap: 5px;')
    expect(styles).toContain('.yuanluobo-panel .yuanluobo-record-row {\n  position: relative;\n  width: 100%;\n  min-height: 88px;\n  display: grid;\n  grid-template-columns: minmax(0, 1fr) 42px;')
    expect(styles).toContain('padding: 16px 20px 16px 58px;')
    expect(styles).toContain('.yuanluobo-panel .yuanluobo-record-row::before {\n  content: "";\n  position: absolute;\n  left: 20px;')
    expect(styles).toContain('.yuanluobo-record-title {\n  min-width: 0;\n  display: inline-flex;')
    expect(styles).toContain('letter-spacing: 0;')
    expect(styles).toContain('.yuanluobo-result-watermark {\n  grid-column: 2;\n  grid-row: 1 / span 2;\n  position: static;')
    expect(styles).toContain('@media (max-height: 560px) and (min-width: 700px) {\n  .yuanluobo-browser {\n    gap: 8px;')
    expect(styles).toContain('.yuanluobo-panel .yuanluobo-record-row {\n    min-height: 72px;\n    grid-template-columns: minmax(0, 1fr) 38px;')
    expect(styles).toContain('.yuanluobo-panel .yuanluobo-record-row::before {\n    left: 18px;\n    top: 14px;\n    bottom: 14px;')
    expect(styles).toContain('@container app-layout (max-width: 699px) {')
    expect(styles).toContain('.yuanluobo-browser {\n    gap: 6px;\n    overflow: hidden;')
    expect(styles).toContain('.game-sidebar.contextual .contextual-titlebar {\n    display: grid;\n    width: 100%;')
    expect(styles).toContain('.yuanluobo-filter-bar {\n    grid-template-columns: minmax(0, 1fr);\n    gap: 6px;')
    expect(styles).toContain('.yuanluobo-panel .yuanluobo-filter-trigger {\n    min-height: 44px;\n    grid-template-columns: 26px auto 1px minmax(0, 1fr) auto;')
    expect(styles).toContain('.yuanluobo-filter-icon {\n    width: 26px;\n    height: 26px;')
    expect(styles).toContain('.yuanluobo-filter-trigger strong {\n    font-size: 14px;')
    expect(styles).toContain('.yuanluobo-panel .yuanluobo-record-row {\n    min-height: 64px;\n    grid-template-columns: minmax(0, 1fr) 30px;')
    expect(styles).toContain('padding: 10px 12px 10px 38px;')
    expect(styles).toContain('.yuanluobo-record-title {\n    gap: 5px;\n    font-size: 14px;')
    expect(styles).toContain('.yuanluobo-record-meta {\n    gap: 6px;\n    font-size: 12px;')
    expect(styles).toContain('.yuanluobo-result-watermark {\n    min-width: 28px;\n    width: 28px;\n    height: 28px;')
    expect(styles).toContain('.yuanluobo-record-row[data-outcome="win"] {')
    expect(styles).toContain('.yuanluobo-record-row[data-outcome="loss"] {')
    expect(styles).toContain('.yuanluobo-record-row[data-outcome="draw"] {')
    expect(styles).toContain('.yuanluobo-result-watermark.win {\n  color: #3f8f66;')
    expect(styles).toContain('.yuanluobo-result-watermark.loss {\n  color: #c86a60;')
    expect(styles).toContain('.yuanluobo-record-row:hover:not(:disabled) {')
    expect(styles).toContain('.yuanluobo-pager {\n  min-height: 40px;')
    expect(styles).toContain('.yuanluobo-picker-backdrop {')
    expect(styles).toContain('.yuanluobo-picker-sheet {\n  position: fixed;')
    expect(styles).toContain('grid-template-rows: auto auto minmax(0, 1fr);')
    expect(styles).not.toContain('.yuanluobo-picker-search')
    expect(styles).toContain('.yuanluobo-panel .yuanluobo-picker-option {\n  width: 100%;\n  min-height: 54px;\n  display: grid;\n  grid-template-columns: 34px minmax(0, 1fr);')
    expect(styles).toContain('.yuanluobo-panel .yuanluobo-picker-option[data-selected=\'true\'] {')
    expect(styles).not.toContain('.yuanluobo-picker-check')
  })

  it('keeps the portrait workspace ordered as toolbar, game info, board, controls, then analysis', () => {
    expect(styles).not.toContain('@media (orientation:')
    expect(styles).toContain('@container app-layout (max-width: 699px) {')
    expect(styles).toContain('grid-template-columns: 1fr;')
    expect(styles).toContain('grid-template-rows: auto auto auto minmax(var(--analysis-bottom-height), 1fr);')
    expect(styles).not.toContain('.rotate-prompt')
    expect(styles).not.toContain('.app-layout {\n    display: none;')
    expect(styles).toContain('.game-sidebar {\n    grid-row: 1;\n    height: auto;\n    min-height: 40px;\n    grid-template-columns: minmax(0, 1fr) auto minmax(0, 1fr);')
    expect(styles).toContain('.sidebar-header {\n    grid-column: 1 / -1;\n    display: contents;')
    expect(styles).toContain('.sidebar-file-actions {\n    grid-column: 1;')
    expect(styles).toContain('.sidebar-toggle-actions {\n    grid-column: 2;\n    justify-self: center;')
    expect(styles).toContain('.board-stage {\n    grid-row: 2;\n    padding: 2px 6px 0;\n    max-height: none;\n    overflow: visible;\n    z-index: 1;')
    expect(styles).toContain('.board-layout {\n    grid-template-columns: 1fr;\n    grid-template-rows: min-content minmax(0, 1fr);\n    gap: 2px;')
    expect(styles).toContain('.board-info {\n    order: 1;\n    gap: 4px;')
    expect(styles).toContain('.board-frame {\n    --board-frame-inline-clearance: 4px;\n    --board-frame-block-clearance: 4px;\n    order: 2;')
    expect(styles).toContain('--portrait-chart-height: 88px;')
    expect(styles).toContain('--portrait-overview-padding-top: 2px;')
    expect(styles).toContain('--analysis-overview-height: calc(var(--portrait-summary-height) + var(--portrait-overview-gap) + var(--portrait-chart-height) + var(--portrait-overview-padding-top) + var(--portrait-overview-padding-bottom));')
    expect(styles).toContain('.action-rail {\n    grid-row: 3;\n    position: relative;\n    z-index: 3;\n    padding: 0 8px 8px;\n    background: transparent;\n    border: 0;')
    expect(styles).toContain('.navigation-controls {\n    width: max-content;\n    max-width: calc(100% - 16px);')
    expect(styles).toContain('border-radius: 999px;\n    background: transparent;\n    box-shadow: none;')
    expect(styles).toContain('overflow: visible;')
    expect(styles).not.toContain('overflow-x: auto;\n    overflow-y: hidden;')
    expect(styles).toContain('.navigation-controls button {\n    width: 32px;\n    min-width: 32px;\n    max-width: 32px;\n    height: 30px;')
    expect(styles).toContain('text-overflow: clip;')
    expect(styles).toContain('.navigation-controls .try-action-button {\n    width: 30px;\n    min-width: 30px;\n    max-width: 30px;\n    height: 30px;\n    padding: 0;')
    expect(styles).toContain('.move-number-stone {\n    width: 30px;\n    height: 30px;')
    expect(styles).toContain('.analysis-rail {\n    grid-row: 4;\n    min-height: 0;\n    max-height: none;\n    grid-template-rows: var(--analysis-overview-height) minmax(var(--analysis-detail-preview-height), 1fr);')
    expect(styles).toContain('.side-action-layout .analysis-rail {\n    grid-row: 3;')
    expect(styles).toContain('padding: 4px 6px 6px;\n    background: var(--board-zone);\n    overflow: hidden;')
    expect(styles).toContain('.analysis-overview,\n  .analysis-detail-tabs {\n    border-color: transparent;\n    background: transparent;\n    box-shadow: none;')
    expect(styles).toContain('.analysis-overview {\n    grid-template-rows: var(--portrait-summary-height) var(--portrait-chart-height);\n    gap: var(--portrait-overview-gap);\n    padding: var(--portrait-overview-padding-top) 6px var(--portrait-overview-padding-bottom);')
    expect(styles).toContain('.chart-body {\n    height: var(--portrait-chart-height);\n    overflow: visible;')
    expect(styles).toContain('.echarts-chart {\n    height: var(--portrait-chart-height);\n    min-height: 0;')
    expect(styles).toContain('.sidebar-analysis {\n    grid-column: 3;\n    grid-row: auto;')
    expect(styles).toContain('.analysis-action-button.analysis-action-wide {\n    width: auto;\n    min-width: 58px;')
  })

  it('uses a foldable portrait workspace with side-by-side analysis below the board', () => {
    expect(styles).not.toContain('@media (orientation:')
    expect(styles).toContain('@container app-layout (min-width: 700px) {')
    expect(styles).toContain('grid-template-rows: auto auto auto minmax(var(--wide-analysis-bottom-height), 1fr);')
    expect(styles).toContain('--wide-analysis-bottom-height: var(--analysis-overview-height);')
    expect(styles).toContain('--side-analysis-height: max(var(--analysis-bottom-height), min(22dvh, 280px));')
    expect(styles).toContain('.app-layout.side-action-layout {\n    grid-template-columns: 1fr;\n    grid-template-rows: auto minmax(0, 1fr) var(--side-analysis-height);')
    expect(styles).toContain('.side-action-layout .game-sidebar {\n    grid-column: 1 / -1;')
    expect(styles).toContain('.side-action-layout .analysis-rail {\n    grid-row: 3;\n    grid-column: 1 / -1;')
    expect(styles).not.toContain('grid-template-rows: auto minmax(0, 1fr) var(--side-action-row-height')
    expect(styles).toContain('.analysis-rail {\n    position: relative;\n    grid-template-columns: minmax(0, 1fr) minmax(0, 1fr);\n    grid-template-rows: minmax(0, 1fr);')
    expect(styles).toContain('grid-row: 4;\n    min-height: 0;')
    expect(styles).toContain('.analysis-overview {\n    position: relative;\n    height: 100%;\n    grid-template-rows: 20px minmax(0, 1fr);')
    expect(styles).toContain('.analysis-detail-tabs {\n    min-height: 0;\n    overflow: hidden;\n    grid-template-rows: 20px minmax(0, 1fr);')
    expect(styles).toContain('.analysis-summary,\n  .analysis-tab-list {\n    height: 20px;')
    expect(styles).toContain('.analysis-overview .chart-body {\n    height: 100%;\n    min-height: 0;')
    expect(styles).toContain('.analysis-detail-tabs .rail-section-body {\n    overflow: auto;')
  })

  it('reserves inline room for the centered right-side action rail beside the board', () => {
    expect(styles).toContain('--board-frame-inline-clearance: 16px;')
    expect(styles).toContain('--board-frame-block-clearance: 16px;')
    expect(styles).toContain('width: min(calc(100cqw - var(--board-frame-inline-clearance)), calc(100cqh - var(--board-frame-block-clearance)));')
    expect(styles).toContain('height: min(calc(100cqw - var(--board-frame-inline-clearance)), calc(100cqh - var(--board-frame-block-clearance)));')
    expect(styles).toContain('.side-action-layout .board-frame {\n  --board-frame-inline-clearance: calc((var(--side-action-width, 42px) + var(--side-action-gap, 18px) + var(--side-action-edge-gap, 12px)) * 2);\n  --board-frame-block-clearance: 16px;')
  })

  it('keeps the non-side-action board sizing override after portrait container rules', () => {
    const widePortraitRules = styles.indexOf('@container app-layout (min-width: 700px) {')
    const stageOverride = styles.lastIndexOf('.app-layout:not(.side-action-layout) .board-stage {')
    const boardOverride = styles.lastIndexOf('.app-layout:not(.side-action-layout) .board-layout {')
    const frameOverride = styles.lastIndexOf('.app-layout:not(.side-action-layout) .board-frame {')

    expect(widePortraitRules).toBeGreaterThan(0)
    expect(stageOverride).toBeGreaterThan(widePortraitRules)
    expect(boardOverride).toBeGreaterThan(widePortraitRules)
    expect(frameOverride).toBeGreaterThan(widePortraitRules)
    expect(styles.slice(stageOverride, stageOverride + 220)).toContain('container-type: inline-size;')
    expect(styles.slice(stageOverride, stageOverride + 220)).toContain('grid-template-rows: auto;')
    expect(styles.slice(boardOverride, boardOverride + 160)).toContain('grid-template-rows: min-content auto;')
    expect(styles.slice(frameOverride, frameOverride + 220)).toContain('height: 100cqw;')
    expect(styles.slice(frameOverride, frameOverride + 220)).toContain('aspect-ratio: 1;')
  })

  it('uses the Yuanluobo record language for touch-first authenticated surfaces', () => {
    expect(styles).toContain('--paper-grid-line: rgb(26 71 42 / 0.04);')
    expect(styles).toContain('--surface-glaze: linear-gradient(180deg, rgb(255 255 255 / 0.97), rgb(252 250 246 / 0.92));')
    expect(styles).toContain('.app-page-workspace::before {')
    expect(styles).toContain('.candidate-row::before,\n.bad-move::before {')
    expect(styles).toContain('.import-url-field {\n  width: min(560px, 100%);')
    expect(styles).toContain('.app-sheet-backdrop {')
    expect(styles).toContain('.app-sheet {')
    expect(styles).toContain('@media (hover: none), (pointer: coarse) {\n  button:not(:disabled):active,')
    expect(styles).toContain('.overlay-toggles .toggle {\n    width: 36px;\n    height: 36px;')
  })

  it('keeps every mobile navigation circle at the same 36px diameter', () => {
    expect(styles).toContain('.navigation-controls button {\n    width: 36px;\n    min-width: 36px;\n    max-width: 36px;\n    height: 36px;')
  })

  it('keeps the try control and move stone the same rendered size on mobile', () => {
    expect(styles).toContain('.move-number-stone {\n  width: var(--ui-move-stone-size);\n  height: var(--ui-move-stone-size);\n  display: grid;\n  place-items: center;\n  justify-self: center;\n  box-sizing: border-box;')
    expect(styles).toContain('.navigation-controls .try-action-button,\n  .move-number-stone {\n    width: 36px;\n    min-width: 36px;\n    max-width: 36px;\n    height: 36px;\n    box-sizing: border-box;')
  })

  it('keeps the try control fill flush with its circular border', () => {
    const tryActionRule = styles.match(/(?:^|\n)(\.navigation-controls \.try-action-button \{[^}]*\})/)?.[1]

    expect(tryActionRule).toBeDefined()
    expect(tryActionRule).toContain('box-shadow: 0 2px 8px rgb(42 30 14 / 0.05);')
    expect(tryActionRule).not.toContain('inset')
  })

  it('keeps the side action rail below the analysis menu stacking context', () => {
    const ruleStart = styles.indexOf('.side-action-layout .action-rail {')
    const sideActionRule = styles.slice(ruleStart, styles.indexOf('}', ruleStart))

    expect(ruleStart).toBeGreaterThan(0)
    expect(sideActionRule).toContain('z-index: 3;')
  })
})
